test build/sonar 5.0

diff --git a/.github/workflows/github_ci_sonarcloud.yml b/.github/workflows/github_ci_sonarcloud.yml
--- a/.github/workflows/github_ci_sonarcloud.yml
+++ b/.github/workflows/github_ci_sonarcloud.yml
@@ -54,18 +54,19 @@ jobs:
           disable-animations: true
           emulator-options: -no-window -gpu swiftshader_indirect -noaudio
           script: |
+            # Attendre que l'émulateur démarre complètement
             timeout=300
             booted=""
             until [[ "$booted" == "1" || $timeout -le 0 ]]; do
-            booted=$(adb -e shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
-            echo "Boot status: $booted"
-            sleep 5
-            timeout=$((timeout-5))
+              booted=$(adb -e shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
+              echo "Boot status: $booted"
+              sleep 5
+              timeout=$((timeout-5))
             done
-          
+      
             if [[ "$booted" != "1" ]]; then
-            echo "Emulator failed to boot in time"
-            exit 1
+              echo "Emulator failed to boot in time"
+              exit 1
             fi
             
             ./gradlew connectedDebugAndroidTest jacocoAndroidTestReport --stacktrace
